# .github/workflows/deploy-frontend.yml
name: Deploy Frontend (SSH)
on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn --frozen-lockfile
      
      - name: Run tests
        run: yarn test:ci

  build-and-deploy:
    # Only run if PR was merged (not just closed) and tests passed
    if: github.event.pull_request.merged == true
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Upload dist
        run: |
          rsync -az --delete --no-times --no-perms -e "ssh -o StrictHostKeyChecking=no" \
            dist/ ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }}:${{ secrets.TARGET_DIR }}/